"""Stable and generated GNU GRUB configuration."""
from __future__ import annotations

import os
import shutil
import tempfile
from pathlib import Path

from .branding import BRAND
from .boot_paths import iso_boot_path
from .errors import FlexBootError
from .manifest import ISORecord
from .process import Runner


def grub_quote(value: str) -> str:
    if any(ord(c) < 32 or ord(c) == 127 for c in value):
        raise FlexBootError("GRUB values may not contain control characters")
    return "'" + value.replace("'", "'\\''") + "'"


def base_config(data_uuid: str) -> str:
    if not data_uuid or any(c not in "0123456789abcdefABCDEF-" for c in data_uuid):
        raise FlexBootError("Invalid or missing data filesystem UUID")
    return f"""# Generated by {BRAND.product_name}. Stable boot configuration.
set default=0
set timeout=-1
set timeout_style=menu
insmod part_gpt
insmod fat
insmod ext2
insmod efi_gop
set gfxmode=auto
insmod gfxterm
insmod gfxterm_background
insmod gfxmenu
insmod png
loadfont ($root)/boot/grub/fonts/unicode.pf2
terminal_output gfxterm
background_image --mode stretch ($root)/boot/grub/themes/flexboot/background.png
search --no-floppy --fs-uuid --set=flexboot_data {data_uuid}
set prefix=($root)/boot/grub
set theme=$prefix/themes/flexboot/theme.txt
export theme
if [ -f ($root)/boot/grub/generated.cfg ]; then
  source ($root)/boot/grub/generated.cfg
fi
menuentry 'UEFI Firmware Settings' {{ fwsetup }}
menuentry 'Reboot' {{ reboot }}
menuentry 'Power Off' {{ halt }}
"""


def generated_config(records: list[ISORecord]) -> str:
    lines = [f"# Generated by {BRAND.product_name}. Manual edits will be replaced.", ""]
    for record in sorted(records, key=lambda item: item.filename.casefold()):
        iso_path = iso_boot_path(record.filename)
        title = f"{record.filename} — {record.profile}"
        plan = record.boot_plan()
        lines.extend([
            f"menuentry {grub_quote(title)} {{",
            f"  set iso_path={grub_quote(iso_path)}",
            "  export iso_path",
            '  loopback loop "($flexboot_data)$iso_path"',
        ])
        if plan.kind == "linux":
            args = plan.args.replace("${iso_path}", '"${iso_path}"')
            lines.append(f"  linux (loop){plan.kernel} {args}")
            lines.append("  initrd " + " ".join(f"(loop){path}" for path in plan.initrds))
        else:
            if plan.remove_tpm_module:
                lines.append("  rmmod tpm")
            lines.extend(["  set root=(loop)", f"  configfile {plan.configfile}"])
        lines.extend(["}", ""])
    return "\n".join(lines)


def atomic_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, raw = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temporary = Path(raw)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        temporary.chmod(0o644)
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)
    try:
        directory_fd = os.open(path.parent, os.O_RDONLY)
        try:
            os.fsync(directory_fd)
        finally:
            os.close(directory_fd)
    except OSError:
        # Some FAT implementations do not support fsync on a directory. The
        # writable mount lifecycle performs syncfs-equivalent flushing too.
        return


def validate_config(path: Path, runner: Runner | None = None) -> bool:
    # grub-script-check reports an empty include as an error even though GRUB can
    # source it safely. The generated file is intentionally empty before ISOs exist.
    if "menuentry" not in path.read_text(encoding="utf-8"):
        return True
    if not shutil.which("grub-script-check"):
        return False
    (runner or Runner()).run(["grub-script-check", str(path)])
    return True


def install_grub(efi_root: Path, runner: Runner) -> None:
    help_result = runner.run(["grub-install", "--help"])
    args = [
        "grub-install", "--target=x86_64-efi", f"--efi-directory={efi_root}",
        f"--boot-directory={efi_root / 'boot'}", "--removable",
    ]
    if "--no-nvram" in help_result.stdout:
        args.append("--no-nvram")
    if "--no-uefi-secure-boot" in help_result.stdout:
        args.append("--no-uefi-secure-boot")
    runner.run(args, capture=False, mutate=True)
    loader = efi_root / "EFI" / "BOOT" / "BOOTX64.EFI"
    if not runner.dry_run and not loader.is_file():
        raise FlexBootError(f"GRUB did not create the removable UEFI loader: {loader}")
